name: graphbit
channels:
- conda-forge
- defaults
dependencies:
- python>=3.11
- pip
- setuptools
- wheel
- git                # For version control operations
- pip:
  - poetry>=1.4.0    # Poetry for dependency management
  - maturin          # For Rust-Python bindings
