site_name: GraphBits AI
theme:
  name: material

nav:
- Home: index.md
- Getting Started:
  - Quickstart: getting-started/quickstart.md
  - Installation: getting-started/installation.md
  - Examples: getting-started/examples.md
- User Guide:
  - Concepts: user-guide/concepts.md
  - Agents: user-guide/agents.md
  - Async vs Sync: user-guide/async-vs-sync.md
  - Dynamics Graph: user-guide/dynamics-graph.md
  - Embeddings: user-guide/embeddings.md
  - LLM Providers: user-guide/llm-providers.md
  - Monitoring: user-guide/monitoring.md
  - Performance: user-guide/performance.md
  - Reliability: user-guide/reliability.md
  - Text Splitters: user-guide/text-splitters.md
  - Validation: user-guide/validation.md
  - Workflow Builder: user-guide/workflow-builder.md
- API Reference:
  - Configuration: api-reference/configuration.md
  - Node Types: api-reference/node-types.md
  - Python API: api-reference/python-api.md
- Connector Integrations:
  - AWS Boto3: connector/aws_boto3.md
  - ChromaDB Integration: connector/chromadb_integration.md
  - FAISS Integration: connector/faiss_integration.md
  - Google Search API: connector/google_search_api.md
  - MariaDB Integration: connector/mariadb_integration.md
  - Milvus Integration: connector/milvus_integration.md
  - MongoDB: connector/mongodb.md
  - PGVector: connector/pgvector.md
  - Pinecone Integration: connector/pinecone_integration.md
  - Qdrant Integration: connector/qdrant_integration.md
  - Weaviate Integration: connector/weaviate_integration.md
- Development:
  - Architecture: development/architecture.md
  - Contributing: development/contributing.md
  - Debugging: development/debugging.md
  - Python Bindings: development/python-bindings.md
- Examples:
  - Comprehensive Pipeline: examples/comprehensive-pipeline.md
  - Content Generation: examples/content-generation.md
  - Data Processing: examples/data-processing.md
  - LLM Integration: examples/llm-integration.md
  - Semantic Search: examples/semantic-search.md
