# Rustfmt configuration for GraphBit

# Basic stable configuration options only
edition = "2021"
hard_tabs = false
max_width = 100
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = false
use_try_shorthand = false

# Note: The following options were removed as they are either:
# - Unknown configuration options: report_fixme, report_todo
# - Nightly-only features: color, condense_wildcard_suffixes, error_on_line_overflow,
# error_on_unformatted, hide_parse_errors, ignore, required_version, skip_children,
# unstable_features
